apiVersion: v1
kind: Secret
metadata:
name: genomica-db-secret
type: Opaque
data:
MYSQL_ROOT_PASSWORD: anVhbl9oaWdpbmlvUFM0=
---
apiVersion: v1
kind: Secret
metadata:
name: clinica-db-secret
type: Opaque
data:
MYSQL_ROOT_PASSWORD: anVhbl9oaWdpbmlvUFM0=
---
apiVersion: v1
kind: Secret
metadata:
name: gateway-db-secret
type: Opaque
data:
MYSQL_ROOT_PASSWORD: anVhbl9oaWdpbmlvUFM0=